// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTDjFKQAf5TGeT94lRuDDcttEvYsZNBt0',
    appId: '1:483632948798:web:9896975f9e9c567f28d36f',
    messagingSenderId: '483632948798',
    projectId: 'flutterauthentication-31f18',
    authDomain: 'flutterauthentication-31f18.firebaseapp.com',
    storageBucket: 'flutterauthentication-31f18.appspot.com',
    measurementId: 'G-TZSVZSDVR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgvhGxAlfXuTfASVaKlmemSxbYAYuFM-k',
    appId: '1:483632948798:android:6a6db4859004db3528d36f',
    messagingSenderId: '483632948798',
    projectId: 'flutterauthentication-31f18',
    storageBucket: 'flutterauthentication-31f18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ws7B2_-8PQKajBn-PKCycMsITHaUIKc',
    appId: '1:483632948798:ios:f8e2dd13f808c18928d36f',
    messagingSenderId: '483632948798',
    projectId: 'flutterauthentication-31f18',
    storageBucket: 'flutterauthentication-31f18.appspot.com',
    iosClientId: '483632948798-r8sp2uv9h67qrgaig3im2jb0ijclodac.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ws7B2_-8PQKajBn-PKCycMsITHaUIKc',
    appId: '1:483632948798:ios:f8e2dd13f808c18928d36f',
    messagingSenderId: '483632948798',
    projectId: 'flutterauthentication-31f18',
    storageBucket: 'flutterauthentication-31f18.appspot.com',
    iosClientId: '483632948798-r8sp2uv9h67qrgaig3im2jb0ijclodac.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocado',
  );
}
