// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXoK4gbIdX4kvm9GKJQUWyXvkPapE1vu8',
    appId: '1:767014164442:web:30bf5bc2a27b0d222cd2e3',
    messagingSenderId: '767014164442',
    projectId: 'flutterfireauthentication',
    authDomain: 'flutterfireauthentication.firebaseapp.com',
    storageBucket: 'flutterfireauthentication.appspot.com',
    measurementId: 'G-3YF7C2PSGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRhzCFUh_NX-j_nOACt_qPrVbVFtMkBs',
    appId: '1:767014164442:android:383a2c6222c4fbcd2cd2e3',
    messagingSenderId: '767014164442',
    projectId: 'flutterfireauthentication',
    storageBucket: 'flutterfireauthentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZvgu9MJGJrr5TFk6a3MflY8ZoYYskGQU',
    appId: '1:767014164442:ios:e6a347d1c78a10f92cd2e3',
    messagingSenderId: '767014164442',
    projectId: 'flutterfireauthentication',
    storageBucket: 'flutterfireauthentication.appspot.com',
    iosClientId: '767014164442-6fglr92t4tav1k1o25jphbo92ocjma3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZvgu9MJGJrr5TFk6a3MflY8ZoYYskGQU',
    appId: '1:767014164442:ios:e6a347d1c78a10f92cd2e3',
    messagingSenderId: '767014164442',
    projectId: 'flutterfireauthentication',
    storageBucket: 'flutterfireauthentication.appspot.com',
    iosClientId: '767014164442-6fglr92t4tav1k1o25jphbo92ocjma3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.avocado',
  );
}
